export * from './Login/Login'
export * from './Home/HomePage'
export * from './Test/TestPage'
export * from './Register/Register'
export * from './Upload/upload'
export * from './Profile/ProfilePage'
export * from './SharePage/SharePage'
export * from './SharePage/SharePageGif'
